### ISSUE TITLE
Gateway CIDR invalid in examples

### ISSUE THREAD

**Issue by ukcloud-rubeon** [UKCloud/documentation#1013]
**Article title**
The title of the article where you've found the problem.

How to build a virtual machine with UKCloud for VMware

**Article file name**
The file name of the article where you've found the problem.

articles/vmware/vmw-gs-build-vm-vcd.md

**Section**
The section in the article where you've found the problem.

Create a network

**Describe the bug**
A clear and concise description of what the problem is.

Example shows Gateway CIDR as 192.168.1.0/24 in screenshot and text.

Following the example results in a vCloud Director error message that the "Gateway cannot be equal to the network definition"

**Solution**
A clear and concise description of what you expected the article to say, if known.

* Screenshot shows Gateway CIDR of 192.168.1.1/24
* Text uses 192.168.1.1/24 as Gateway CIDR example

**Additional context**
Add any other context about the problem here, for example, browser used.

**Comment by suehighmoor** [comment]
Apologies that it's taken so long to follow up on a simple request. Fix has been made in PR #1892, just waiting for review and approval before merging and publishing.
