### ISSUE TITLE
Hystax Guide ESXi reference.

### ISSUE THREAD

**Issue by koneill94** [UKCloud/documentation#1030]
**Article title**
How to migrate workloads on OpenStack using Hystax Acura | UKCloud Ltd

**Article file name**
ostack-how-use-hystax.md

**Section**
Migrating OpenStack workloads

**Describe the bug**
Point 4. "When any of the agents are deployed, the machine with it (or all machines on the same ESXi host where the agent is located) will appear in Hystax Acura Control Panel under customer dashboard in the Discovered state." the reference to machines on an ESXi host for an OpenStack migration appears to be an error.

**Solution**

**Additional context**

**Comment by suehighmoor** [comment]
Thanks for pointing this out. Fixed in PR #1040
