### ISSUE TITLE
Multi-CLoud Backup Service doesnt exist

### ISSUE THREAD

**Issue by simonrowan** [UKCloud/documentation#1072]
These pages should be removed as the service was never built, Product Management should be able to confirm
https://docs.ukcloud.com/articles/other/other-faq-mcbs.html
https://docs.ukcloud.com/articles/other/other-sd-mcbs.html

**Comment by suehighmoor** [comment]
Awaiting decision on official product retirement

**Comment by suehighmoor** [comment]
We're currently working through the doc to make it clear which articles relate to retired products, so this should be resolved soon.

**Comment by suehighmoor** [comment]
Finally got around to this as part of the product retirement process
