### ISSUE TITLE
System Center on the UKCloud platform

### ISSUE THREAD

**Issue by bartchal** [UKCloud/documentation#1075]
**Article title**
System Center on the UKCloud platform

**Article file name**
https://docs.ukcloud.com/articles/vmware/vmw-ref-system-center.html

**Section**
main body

**Describe the bug**
missing link where text says 'Further detail and guidance regarding this process can be found here.'
there is no link to the further information

**Solution**
add in the hyperlink to whatever the additional info is...

**Additional context**
Add any other context about the problem here, for example, browser used.

**Comment by suehighmoor** [comment]
PRs have been reviewed and approved. System Centre info is now up to date.
