### ISSUE TITLE
Image regarding Regions / Zones not updated

### ISSUE THREAD

**Issue by jmccukc** [UKCloud/documentation#1593]
**Article title**
UKCloud services by region

**Article file name**
https://docs.ukcloud.com/articles/other/other-ref-services-by-region.html

**Section**
https://docs.ukcloud.com/articles/other/other-ref-services-by-region.html#sites-regions-and-zones

**Describe the bug**
the image presented does NOT include the new regions  13 and 14 outlined in the text below.

**Solution**
image to be updated.

**Additional context**
none.

**Comment by suehighmoor** [comment]
Thanks for spotting this; will get the image updates to include the new regions.

**Comment by suehighmoor** [comment]
Image has been updated, just waiting for PR approval
