### ISSUE TITLE
OpenStack Octavia documentation  link returns 404 error 

### ISSUE THREAD

**Issue by bmangesh** [UKCloud/documentation#2048]
I was browsing https://docs.ukcloud.com/articles/other/other-ref-high-availability.html , and found out that below link is returning 404 error. looks like RedHat moved the link to diffrent location
[old link](https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html/networking_guide/sec-octavia)

below is the correct link 

[New link](https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/using_octavia_for_load_balancing-as-a-service/index)

**Comment by suehighmoor** [comment]
Thank you very much for taking the time to let us know about this broken link and for providing an alternative link.
This issue is being addressed in PR #2018, along with other updates to this article.
