### ISSUE TITLE
28/08/2022 - How to install and use Red Hat Update Infrastructure (RHUI 3) - Review required

### ISSUE THREAD

**Issue by suehighmoor** [UKCloud/documentation#2757]
:page_facing_up: Title - How to install and use Red Hat Update Infrastructure (RHUI 3)
:calendar: Expires - 28/08/2022
:family: Team - Product Marketing Review Team
:package: Product - Shared Services
:link: [GitHub Link](https://github.com/UKCloud/documentation/tree/master/articles/shared/shared-how-install-rhui-vm-3.md)
:link: [Knowledge Centre Link](https://docs.ukcloud.com/articles/shared/shared-how-install-rhui-vm-3.html)

**Before making any changes, make sure you're familiar with our [guidelines](https://docs.ukcloud.com/articles/other/other-ref-knowledge-guidelines.html) for contributing to Knowledge Centre articles.**

**Comment by cantlep** [comment]
No changes required for this.
