### ISSUE TITLE
Where can the Heat Template be found?

### ISSUE THREAD

**Issue by AdamStockley** [UKCloud/documentation#469]
Article states:
"Fully scripted repeatable deployment (HEAT template available on the UKCloud Knowledge Centre alongside this article)"

The Heat template does not appear to be available via Docs, and there's no link in the article - would it be possible to update with a link to the Heat template please?

**Comment by suehighmoor** [comment]
Article: Creating load-balancing services on UKCloud for OpenStack - ostack-how-create-load-balancer.md

**Comment by suehighmoor** [comment]
Thank you for bringing this issue to our attention. We're currently looking at alternative ways to make this template available. In the meantime, you can download it from the old Knowledge Centre (Portal login required):
https://portal.skyscapecloud.com/support/knowledge_centre/26876fee-c7bf-40bc-b257-fae506ee35ef/attachment/1

**Comment by suehighmoor** [comment]
The HEAT template is now available here: https://cas.frn00006.ukcloud.com/Docs/Documents/OpenStack-LBaaS.zip?AWSAccessKeyId=438-1048-5-aefff7-1&Expires=1601391847&Signature=HUI%2Bp79N44gmGz2btqoFZTQsf%2Fc%3D
Article updated with new location.
