### ISSUE TITLE
Broken links on 9 articles

### ISSUE THREAD

**Issue by ccouzens** [UKCloud/documentation#836]
I ran a link checker, and it highlighted the following articles as having broken links.
I would submit a pull request to fix them, but I don't know where they're meant to go to.

cloud-storage/cs-gs.md
├─BROKEN─ https://www.emc.com/collateral/TechnicalDocument/docu68370.pdf (HTTP_404)

connectivity/conn-faq.md
├─BROKEN─ http://www.cesg.gov.uk/servicecatalogue/service_assurance/CAS/Pages/Service-Requirements.aspx (ERRNO_ENOTFOUND)
├─BROKEN─ https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/81660/PSN-IP-Address-Allocation-Guidance-v1-4.pdf (HTTP_404)

cdsz/cdsz-gs-walled-garden.md
├─BROKEN─ https://www.ncsc.gov.uk/index/professional-service?f%5B0%5D=field_assurance_status%3AAssured&f%5B1%5D=field_assurance_scheme%3A213 (HTTP_404)

azure/azs-how-configure-powershell-users.md
├─BROKEN─ https://docs.microsoft.com/en-us/powershell/wmf/5.1/install-configure (HTTP_404)
├─BROKEN─ https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-stack/user/azure-stack-develop-templates.md (HTTP_404)

azure/azs-how-use-azure-api.md
├─BROKEN─ https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-stack/azure-stack-provider-resource-api.md (HTTP_404)

azure/azs-how-deploy-sql-template-powershell.md
├─BROKEN─ https://github.com/Azure/AzureStack-QuickStart-Templates/tree/master/sql-2016-ha (HTTP_404)
├─BROKEN─ https://github.com/Azure/AzureStack-QuickStart-Templates/tree/master/sql-2016-ha (HTTP_404)

cloud-storage/cs-how-use-file-browsers.md
├─BROKEN─ https://cas.frn00006.ukcloud.com/Docs/Cloud_Storage/AtmosHTML5.zip?AWSAccessKeyId=438-1048-5-aefff7-1&Expires=1575471403&Signature=49Xss9swLLmSPmkAyruywkscUas%3D (HTTP_403)
├─BROKEN─ https://developer-content.emc.com/downloads/jive_attach_proxy.htm?ecnCommID=3939&ecnCommName=ECS%20-%20Elastic%20Cloud%20Storage&ecnAttachmentName=EMC%20ECS%20S3%20(HTTPS%20with%20AWS2).cyberduckprofile&ecnContainerURL=/docs/DOC-27683&reqURL=/servlet/JiveServlet/download/27683-11-131318/EMC%20ECS%20S3%20(HTTPS%20with%20AWS2).cyberduckprofile (ERRNO_ECONNRESET)

mcbs/mcbs-faq.md
├─BROKEN─ https://www.emc.com/collateral/TechnicalDocument/docu91897.pdf (HTTP_404)

azure/azs-how-configure-cli.md
├─BROKEN─ https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-stack/user/azure-stack-deploy-template-command-line.md (HTTP_404)

**Comment by ccouzens** [comment]
Technical details:
I used [broken-link-checker](https://github.com/stevenvachon/broken-link-checker) to run
```bash
blc --recursive --input http://localhost:8000/
```

I then removed some of the results, because they did seem to be resolving for me.

**Comment by suehighmoor** [comment]
Mostly done - just need clarification about what to do with MCBS - may remove these articles in their entirety.

**Comment by suehighmoor** [comment]
All broken links should now be fixed.
