### ISSUE TITLE
No definition for requests

### ISSUE THREAD

**Issue by DBroderick** [UKCloud/documentation#882]
**Article title**
How to raise and escalate support tickets (incidents and service requests) with customer support

**Article file name**
https://docs.ukcloud.com/articles/portal/ptl-how-raise-escalate-service-request.html?q=incident.

**Section**
Incident priorities.

**Describe the bug**
We only define incidents here, not requests. Additionally, only the P1 says "in progress" - Usual interpretation on the backend is that if a problem is fixed and the customer wants to raise a ticket for an explanation, then it should be raised as a request, however, this is not clear in the definitions here.

**Solution**
Need to specify in P2-4 if it is in progress or not to be an Incident
Define a Request

**Additional context**
Normal interpretation of tickets by triage is: Incident is something which is currently broken. Request is asking for information, a change to config and similar.

**Comment by suehighmoor** [comment]
Updated in PR #927

**Comment by suehighmoor** [comment]
Article has been updated. Thanks for the feedback!
