### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by simonrowan** [UKCloud/documentation#889]
In this doc https://docs.ukcloud.com/articles/vmware/vmw-ref-edge-ha.html#feedback

The "High Availability Blueprint" link produces a 404 error

**Comment by suehighmoor** [comment]
https://github.com/UKCloud/documentation/pull/890

**Comment by suehighmoor** [comment]
Thanks for raising this issue.
Link now points to new High Availability article on the Knowledge Centre.
