### ISSUE TITLE
Multi-Cloud Backup Service

### ISSUE THREAD

**Issue by simonrowan** [UKCloud/documentation#894]
This doesnt actually exist as a service so we should hide the documentation from customers. I doubt very much it will exist in the future in this state as Guy is looking at a Veaam based solution 
I can find 3 references:
https://docs.ukcloud.com/articles/mcbs/mcbs-gs.html?q=multi-cloud%20backup
https://docs.ukcloud.com/articles/mcbs/mcbs-faq.html?q=multi-cloud%20backup
https://docs.ukcloud.com/articles/mcbs/mcbs-sd.html?q=multi-cloud%20backup

**Comment by suehighmoor** [comment]
We still need to keep these around as the service is used to support other services (e.g., Trilio for OpenStack). I've removed MCBS from the home page to reduce visibility. Articles are now available under "Other".
